# Generated by Django 3.0.8 on 2020-07-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdie_app', '0002_auto_20200702_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdie',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='birdie',
            name='player',
            field=models.CharField(blank=True, choices=[('bryan', 'Bryan'), ('david', 'David'), ('greg', 'Greg'), ('steve', 'Steve')], max_length=10, null=True),
        ),
    ]
