# Generated by Django 3.0.8 on 2020-07-03 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdie_app', '0004_auto_20200702_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdie',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
