# Generated by Django 3.0.8 on 2020-07-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdie_app', '0005_auto_20200703_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdie',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
