# Generated by Django 3.0.8 on 2020-11-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdie_app', '0010_auto_20200922_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdie',
            name='course',
            field=models.CharField(blank=True, choices=[('Broadmoor', 'Broadmoor'), ('Camas Meadows', 'Camas Meadows'), ('Colwood', 'Colwood'), ('Heron Lakes Great Blue', 'Heron Lakes Great Blue'), ('Heron Lakes Greenback', 'Heron Lakes Greenback'), ('Lewis River', 'Lewis River'), ('Riverside Golf Club', 'Riverside Golf Club'), ('Tri Mountain', 'Tri Mountain')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='birdie',
            name='hole',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18')], null=True),
        ),
    ]
